"""
Django settings for amsProj project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_7u&s9wrcl+l03@y5%6brf^sv745_t=0i3ni)@*s_lxz@jej!0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #True 

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api',
    'amsApp',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'amsApp.middleware.HRISAuthenticationMiddleware',  
]

ROOT_URLCONF = 'amsProj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'amsApp', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amsProj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
TIME_ZONE = 'Asia/Manila'
USE_TZ = False

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    # for local 
      "default": {
        "ENGINE": 'django.db.backends.mysql',
        "NAME": 'ams',
        "USER": 'root',
        "PASSWORD": '',
        "HOST": 'localhost',
        "PORT": '3306',
        'OPTIONS': {
            'init_command': "SET time_zone = '+08:00';",
        },
      },

    #  FOR ubuntu
    #  "default": {
    #     "ENGINE": 'django.db.backends.mysql',
    #     "NAME": 'ams',
    #     "USER": 'bobby',
    #     "PASSWORD": '@Sdmd1234',
    #     "HOST": 'localhost',
    #     "PORT": '3306',
    #       'OPTIONS': {
    #         'init_command': "SET time_zone = '+08:00';",
    #     },
    # }
  

}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'amsApp', 'static'),  # App-specific static files
# ]

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS Configuration
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",  # Replace with your Flutter app's URL or IP
#     "http://127.0.0.1:3000",  # Add other origins as needed
# ]

# Alternatively, allow all origins (not recommended for production):
CORS_ALLOW_ALL_ORIGINS = True


# Allow credentials if needed
CORS_ALLOW_CREDENTIALS = True

# Explicitly allow the headers your Flutter app sends
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',        # Your custom header
    'x-signature',      # Your custom header  
    'x-timestamp',      # Your custom header
]

# Allow the HTTP methods your API uses
CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH', 
    'POST',
    'PUT',
]


# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

#Celery Configuration

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

#authentication
HRIS_API_URL = "https://hris.usep.edu.ph/api/dashboard/login"
HRIS_API_TOKEN = "496871859d96697ba10536775445fd8f"  # Ideally from env vars
HRIS_TIMEOUT = 5 

# API Authentication Settings
FLUTTER_API_KEYS = [
    'USeP-1234-AMS-321-API-000-key-12345',
    '1234-USeP-321-AMS-000-API-12345-key',
]

FLUTTER_API_SECRET = 'B3o1b3b3y1'

FLUTTER_API_TOKENS = [
    'USeP-AMS-bearer-token-abc123def456',
    'USeP-AMS-backup-bearer-token-xyz789uvw012',
]