# Generated by Django 5.1.7 on 2025-03-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManShift',
            fields=[
                ('shiftNo', models.AutoField(primary_key=True, serialize=False)),
                ('shiftName', models.CharField(max_length=200)),
                ('shiftTypeNo', models.CharField(max_length=2)),
                ('breakNo', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=500)),
                ('startTime', models.CharField(max_length=8)),
                ('endTime', models.CharField(max_length=8)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_shift',
            },
        ),
        migrations.CreateModel(
            name='ManShiftBreak',
            fields=[
                ('breakNo', models.AutoField(primary_key=True, serialize=False)),
                ('breakName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('startTime', models.CharField(max_length=8)),
                ('endTime', models.CharField(max_length=8)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_shift_break',
            },
        ),
        migrations.CreateModel(
            name='ManShiftType',
            fields=[
                ('shiftTypeNo', models.AutoField(primary_key=True, serialize=False)),
                ('shiftType', models.CharField(max_length=50)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_shift_type',
            },
        ),
        migrations.CreateModel(
            name='PunchLog',
            fields=[
                ('punchNo', models.AutoField(primary_key=True, serialize=False)),
                ('shiftNo', models.CharField(max_length=8)),
                ('empId', models.CharField(max_length=20)),
                ('punchdate', models.DateField()),
                ('punchTimeIn', models.CharField(max_length=8)),
                ('punchTimeOut', models.CharField(max_length=8)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('systemDateTime', models.DateTimeField()),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'punch_log',
            },
        ),
    ]
