# Generated by Django 5.1.7 on 2025-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchlog',
            name='employee',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
