# Generated by Django 5.1.7 on 2025-04-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0002_punchlog_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchlog',
            name='systemDateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
