# Generated by Django 5.1.7 on 2025-05-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0004_punchlog_pdsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='sysInfo',
            fields=[
                ('sysId', models.AutoField(primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=50)),
                ('sysValue', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sys_info',
            },
        ),
    ]
