# Generated by Django 5.1.7 on 2025-05-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0005_sysinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManEvent',
            fields=[
                ('eventNo', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=200)),
                ('eventType', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=500)),
                ('startTime', models.CharField(max_length=8)),
                ('startBefore', models.CharField(max_length=8)),
                ('endTime', models.CharField(max_length=8)),
                ('endAfter', models.CharField(max_length=8)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_event',
            },
        ),
        migrations.CreateModel(
            name='ManEventType',
            fields=[
                ('eventTypeNo', models.AutoField(primary_key=True, serialize=False)),
                ('eventType', models.CharField(max_length=50)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_event_type',
            },
        ),
        migrations.CreateModel(
            name='ManLocation',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('locName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_location',
            },
        ),
        migrations.CreateModel(
            name='ManLocationDet',
            fields=[
                ('ctrlNo', models.AutoField(primary_key=True, serialize=False)),
                ('locationId', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=15)),
                ('latitude', models.CharField(max_length=15)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_location_det',
            },
        ),
        migrations.RenameField(
            model_name='punchlog',
            old_name='shiftNo',
            new_name='eventNo',
        ),
    ]
