# Generated by Django 5.1.7 on 2025-05-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0007_rename_eventtype_manevent_eventtypeno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manevent',
            name='endAfter',
        ),
        migrations.RemoveField(
            model_name='manevent',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='manevent',
            name='startBefore',
        ),
        migrations.RemoveField(
            model_name='manevent',
            name='startTime',
        ),
    ]
