# Generated by Django 5.1.7 on 2025-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0010_manschedule_locationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='manschedule',
            name='isSet',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='manschedule',
            name='recurrenceDays',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
