# Generated by Django 5.1.7 on 2025-06-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0011_manschedule_isset_alter_manschedule_recurrencedays'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchlog',
            name='office',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='punchlog',
            name='officeId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
