# Generated by Django 5.1.7 on 2025-07-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0013_tamperpunchlog_remove_punchlog_systemdatetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tamperPunchLog',
        ),
    ]
