# Generated by Django 5.1.7 on 2025-07-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0015_punchlogtamper'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatedPunchLog',
            fields=[
                ('evalPunchNo', models.AutoField(primary_key=True, serialize=False)),
                ('eventNo', models.CharField(max_length=8)),
                ('empId', models.CharField(max_length=20)),
                ('pdsId', models.CharField(max_length=20, null=True)),
                ('employee', models.CharField(max_length=150, null=True)),
                ('punchdate', models.DateField()),
                ('punchTimeIn', models.CharField(max_length=8)),
                ('punchTimeOut', models.CharField(max_length=8)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('officeId', models.CharField(blank=True, max_length=10, null=True)),
                ('office', models.CharField(blank=True, max_length=400, null=True)),
                ('systemDateTime', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'punch_log_eval',
            },
        ),
    ]
