# Generated by Django 5.1.7 on 2025-07-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0016_evaluatedpunchlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluatedPunchLog',
        ),
    ]
