# Generated by Django 5.1.7 on 2025-07-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0020_evaluatedpunchlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluatedPunchLog',
        ),
    ]
