# Generated by Django 5.1.7 on 2025-07-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0023_delete_evaluatedpunchlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatedPunchLog',
            fields=[
                ('evalPunchNo', models.AutoField(primary_key=True, serialize=False)),
                ('punchNo', models.CharField(max_length=10)),
                ('eventNo', models.CharField(max_length=8)),
                ('empId', models.CharField(max_length=20)),
                ('pdsId', models.CharField(max_length=20, null=True)),
                ('employee', models.CharField(max_length=150, null=True)),
                ('empStatus', models.CharField(max_length=50)),
                ('empType', models.CharField(max_length=30)),
                ('empRank', models.CharField(max_length=200)),
                ('punchdate', models.DateField()),
                ('punchTimeIn', models.CharField(max_length=8)),
                ('punchTimeOut', models.CharField(max_length=8)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('officeId', models.CharField(blank=True, max_length=10, null=True)),
                ('office', models.CharField(blank=True, max_length=400, null=True)),
                ('campusId', models.CharField(max_length=8)),
                ('campus', models.CharField(max_length=30)),
                ('systemDateTime', models.DateTimeField(blank=True, null=True)),
                ('attStatusId', models.CharField(max_length=1)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'punch_log_eval',
            },
        ),
    ]
