# Generated by Django 5.1.7 on 2025-07-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0024_evaluatedpunchlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysPunchStatus',
            fields=[
                ('sysEvalId', models.AutoField(primary_key=True, serialize=False)),
                ('punchName', models.CharField(max_length=20)),
                ('punchCount', models.CharField(max_length=20)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'sys_punch',
            },
        ),
    ]
