# Generated by Django 5.1.7 on 2025-07-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0025_syspunchstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SysPunchStatus',
        ),
    ]
