# Generated by Django 5.1.7 on 2025-08-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0028_cancelledschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancelledSchedule',
        ),
    ]
