# Generated by Django 5.1.7 on 2025-08-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0029_delete_cancelledschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledSchedule',
            fields=[
                ('cancelledId', models.AutoField(primary_key=True, serialize=False)),
                ('schedId', models.CharField(max_length=10)),
                ('cancelledDate', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('cancelledBy', models.CharField(blank=True, max_length=100, null=True)),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cancelled_schedule',
            },
        ),
    ]
