# Generated by Django 5.1.7 on 2025-08-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0030_cancelledschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SysPunchStatus',
        ),
    ]
