# Generated by Django 5.1.7 on 2025-08-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0031_delete_syspunchstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysPunchStatus',
            fields=[
                ('sysEvalId', models.AutoField(primary_key=True, serialize=False)),
                ('punchName', models.CharField(max_length=20)),
                ('punchLastPkey', models.CharField(max_length=20)),
                ('punchLastDate', models.DateField(blank=True, null=True)),
                ('punchCount', models.CharField(max_length=20)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'sys_punch',
            },
        ),
    ]
