# Generated by Django 5.1.7 on 2025-08-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0032_syspunchstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashUsers',
            fields=[
                ('empId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pdsId', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.CharField(blank=True, max_length=150, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'dash_users',
            },
        ),
    ]
