# Generated by Django 5.1.7 on 2025-08-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0034_punchlog_locationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatedpunchlog',
            name='locationId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='punchlogtamper',
            name='locationId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
